title: "Baja R/C Competition Car"
email: "alex.amadio@outlook.com"
author: "Alex Amadio"
description: "College senior project blog and documentation"
baseurl: "" # the subpath of your site, e.g. /project
url: "https://aaeygui.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-diagrams

markdown: kramdown

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - color-functions
    - global-builtin

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
